### ISSUE TITLE
Deletion of posts/activities outside of course during unenroll

### ISSUE THREAD

**Issue by logan-reynolds** [synergylearning/moodle-format_socialwall#11]
- If the 'Delete Items after unenrol user' setting is enabled in a restored course and the original course still exists (ie. there are duplicate courses), deleting the restored course will also delete posts in the original course.  This appears to be because the cleanup_userunrenolled function which is called in the autoloaded classes/local/posts.php file deletes _all_ user posts on line 111, when it should only delete posts in the course they are being unenrolled from:    self::delete_users_posts($userid);
- If the 'Automatically delete activities' setting is also enabled in the restored course, deleting the duplicate course may also delete some activities in the original course as well (this behaviour was inconsistent during testing.)  The root cause is likely a similar issue as above with needing to add additional conditions which limit the deletion to only activities within the course being deleted.

**Comment by awagner** [comment]
Hi Logan, 

thanks a lot for reporting this issue. Curious, that this wasn't recognized yet....
I will fix this asap.

Kind regards
Andi

**Comment by awagner** [comment]
Hi all, 

issue is fixed and a new version is provided.

Thanks again
Andi
