### ISSUE TITLE
Hard-coded English language strings

### ISSUE THREAD

**Issue by germanvaleroelizondo** [synergylearning/moodle-format_socialwall#4]
Hi,
I like your socialwall format for Moodle plugin. I translated the English language plugins in AMOS (https://lang.moodle.org) to the Mexican Spanish language pack. There is also a Brazilian Portuguese language pack already available for this plugin.

I think this very nice plugin would be even better if some English language strings that are currently hard-wired were converted into variables, so that they would be available for translation in AMOS.

So far, the following hard-wired English language strings I have found are:
"Message"
"Comments"
"Post"
"Attachments"

I would also dare to suggest you to change  turneditoron | format_socialwall which currently is 'HTML-Editor on' into 'Turn HTML-Editor on' , as this new string will be easier for most translators and users in languages other than English.
And the same goes for  turneditoroff | format_socialwall 'HTML-Editor off' into 'Turn HTML-Editor off'.

Thanks in advance for your help and for a very nice plugin :)

**Comment by awagner** [comment]
Hi, 

thanks a lot for your translation and your suggestions. There will be a new version (including new features) in the next few month. We will fix found issues then.

Thanks again

**Comment by awagner** [comment]
Hi germanvaleroelizondo,

i'm about to update the plugin, but i can't find the hard wired strings. Can you please give me more details, where you have found it (i. e. in which file they are?)

**Comment by germanvaleroelizondo** [comment]
Hi,
The hard-coded English language strings only show when I select the Evolve-D theme (https://moodle.org/plugins/view/theme_evolved). So, I think it might be a theme-related issue appearing on this socialwall format, and not a format-related issue. I apologize :(  I'll get in touch with the theme author (Chris Kenniburg), who is also a co-author of this plugin.

BTW: An easy way to see these hard-wired strings is by choosing the Mexican Spanish language pack (100% translation of both plugins in AMOS) and noticing the English language strings.
![hard-wired english strings in evolve-d theme](https://cloud.githubusercontent.com/assets/2671923/8990951/1f2ce668-36bb-11e5-909a-dbddc24fe910.png).

Thanks a lot

**Comment by kennibc** [comment]
Those are indeed part of the CSS for the Evolve-D theme. They are used in a content string in the CSS starting around line 766 of the evolved.css file.

You can easily change the text. Or if you want to help I don't know how to use a language string in CSS.

.format-socialwall ul.section.tl-postattachment:before {
content: "\f0c6 Attachments";
color:#A83116;
line-height: 20px;
horizontal-aling: ;
display: inline-block;
font: 16px/1 FontAwesome;
text-rendering: auto;
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
transform: translate(0, 0);
margin-bottom: 7px;
margin-left:-15px;
padding-bottom: 4px;
border-bottom:2px solid #ccc;
}
.format-socialwall .tl-comments:before {
content: "\f0e6 Comments";
color:#A83116;
line-height: 20px;
horizontal-aling: ;
display: inline-block;
font: 16px/1 FontAwesome;
text-rendering: auto;
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
transform: translate(0, 0);
margin-bottom: 7px;
padding-bottom: 4px;
width:100%;
text-align: center;
}

.format-socialwall .tl-posttext:before{
content: "\f0e5 Message";
color:#A83116;
line-height: 20px;
horizontal-aling: ;
display: inline-block;
font: 16px/1 FontAwesome;
text-rendering: auto;
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
transform: translate(0, 0);
margin-bottom: 7px;
padding-bottom: 4px;
border-bottom:2px solid #ccc;
width:100%;
text-align: center;
}

.format-socialwall .tl-post:before{
content: "\f086 Post";
color:#A83116;
line-height: 20px;
horizontal-aling: ;
display: inline-block;
font: 18px/1 FontAwesome;
text-rendering: auto;
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
transform: translate(0, 0);
padding-bottom: 4px;
padding-left:15px;
text-align: center;
}
