### ISSUE TITLE
Guest user can post status or note 

### ISSUE THREAD

**Issue by murilotimo** [synergylearning/moodle-format_socialwall#6]
Hi,
Congratulations for the plugin

I want to create a course in SocialWall format, which can be seen by visitors, but only students can post.
But here the guest User is managing to post.
It is a security breach? I have not found that allowed for posts.
in the format/socialwall:posthtml permission i have only the teacher

**Comment by awagner** [comment]
Hi, 

thanks for you cheers. There will be a new release at the end of october introducing a new capability for writing a post, which solves your problem.
