### ISSUE TITLE
Missing language strings

### ISSUE THREAD

**Issue by ewallah** [synergylearning/moodle-format_socialwall#7]
Invalid get_string() identifier: 'cachedef_commentformerrors' or component 'format_socialwall'. Perhaps you are missing $string['cachedef_commentformerrors'] = '';
Invalid get_string() identifier: 'cachedef_postformerrors' or component 'format_socialwall'. Perhaps you are missing $string['cachedef_postformerrors'] = ''; 
Invalid get_string() identifier: 'cachedef_postformparams' or component 'format_socialwall'. Perhaps you are missing $string['cachedef_postformparams'] = ''

Moodle 2.9.3

**Comment by awagner** [comment]
Thanks, will be fixed in the next release.
