### ISSUE TITLE
Invalid get_string() identifier: 'cachedef_attachedrecentactivities'

### ISSUE THREAD

**Issue by ewallah** [synergylearning/moodle-format_socialwall#8]
Invalid get_string() identifier: 'cachedef_attachedrecentactivities' or component 'format_socialwall'. Perhaps you are missing $string['cachedef_attachedrecentactivities'] = ''; in lang/en/format_socialwall.php?

**Comment by awagner** [comment]
Thanks for reporting this issue, it is fixed in the latest version of plugin.

Kind regards
Andi
